### ISSUE TITLE
Would anyone value discourse for most conversational stuff?

### ISSUE THREAD

**Issue by zmoazeni** [our-stories/west-marches#59]
I'm thinking this stuff would be much better in a forum like discourse rather than GitHub:

* Introducing characters
* RPing your own character, to build out their backstory and perhaps flesh out their development as they play
* Starting and managing ongoing session

And then we could shut down the wiki and have GitHub be a central repository of all firm lore in and around Waldenstone.

Would anyone else find value in that? I'm thinking of setting it up and trying it out to see what people tend to gravitate towards.

**Comment by DanielOhn** [comment]
I think it would be better if we had a more forum based option for the character information and sessions.  I tend to use Github for more work and personal projects, but it's your guy's decision in the end.   I don't mind using Github since I'm already used to it and know how a majority of the features work, but it might be a little off putting to newcomers.

**Comment by zmoazeni** [comment]
@crimsonknave Just enabled Discussions for this repo, so we can try that a bit before moving to an external service. Hopefully discussions are less intimidating than issues or pull requests. And we can avoid having two separate areas that "stuff" is maintained.

![west-marches 2020-08-25 15-33-34](https://user-images.githubusercontent.com/314/91219392-908a3800-e6e8-11ea-8031-c44c0ca553d3.png)


@DanielOhn I agree with you. I think it's a bit of a turn-off. Perhaps discourse will still be kinder. I dunno. I'm willing to give Discussions a shot for now and we can revisit in a few weeks.
